import "./styles/fonts.scss";
import "./styles/gallery.scss";
import "./styles/gradient.scss";
import "./styles/nav.scss";
import "./styles/news.scss";
import "./styles/normalize.css";
import "./styles/position.scss";
import "./styles/table.scss";
import "./styles/print.css";
